#define DATABASE_SIZE 1370
std::string ehc_fncs[DATABASE_SIZE] = {
"acpi_bus_unregister_driver" ,"acpi_disable_wakeup_device_power" ,"acpi_ec_stop" ,
"acpi_exception" ,"acpi_exception" ,"acpi_os_free" ,
"acpi_os_free" ,"acpi_os_release_lock" ,"acpi_os_unmap_memory" ,
"acpi_processor_unregister_performance" ,"acpi_put_table" ,"acpi_unlock_hp_context" ,
"acpi_unmap_cpu" ,"acpi_ut_release_mutex" ,"acpi_ut_remove_reference" ,
"acpi_ut_remove_reference" ,"acpi_ut_remove_reference" ,"afs_put_call" ,
"afs_put_cell" ,"afs_put_wb_key" ,"agp_free_memory_wrap" ,
"ahci_rpm_put_port" ,"ata_host_put" ,"atomic64_sub" ,
"atomic_dec_and_test" ,"atomic_dec_and_test" ,"atomic_dec" ,
"atomic_dec" ,"atomic_dec" ,"atomic_dec" ,
"atomic_dec" ,"atomic_dec" ,"atomic_inc" ,
"atomic_long_sub" ,"atomic_sub" ,"atomic_sub" ,
"audit_free_parent" ,"batadv_gw_node_put" ,"batadv_gw_node_put" ,
"batadv_hardif_neigh_put" ,"batadv_hardif_put" ,"batadv_hardif_put" ,
"batadv_hardif_put" ,"batadv_hardif_put" ,"batadv_hardif_put" ,
"batadv_hardif_put" ,"batadv_neigh_ifinfo_put" ,"batadv_neigh_ifinfo_put" ,
"batadv_neigh_node_put" ,"batadv_neigh_node_put" ,"batadv_orig_node_put" ,
"batadv_orig_node_put" ,"batadv_orig_node_put" ,"batadv_orig_node_put" ,
"batadv_softif_vlan_put" ,"batadv_tp_vars_put" ,"bdi_put" ,
"bdi_put" ,"bdput" ,"bdput" ,
"_binder_inner_proc_unlock" ,"_binder_proc_unlock" ,"binder_put_node" ,
"bio_free_pages" ,"bio_put" ,"bio_put" ,
"bitmap_free" ,"blkdev_put" ,"blk_finish_plug" ,
"blk_mq_free_tag_set" ,"blk_mq_unfreeze_queue" ,"blktrans_dev_put" ,
"block2mtd_free_device" ,"bpf_array_free_percpu" ,"bpf_cgroup_storage_free" ,
"bpf_cgroup_storages_free" ,"bpf_jit_prog_release_other" ,"__bpf_prog_free" ,
"bpf_prog_sub" ,"bpf_sk_storage_diag_free" ,"brelse" ,
"brelse" ,"brelse" ,"brelse" ,
"brelse" ,"brelse" ,"btf_verifier_env_free" ,
"__btf_verifier_log_type" ,"btree_node_free" ,"btrfs_backref_free_edge" ,
"btrfs_backref_iter_free" ,"btrfs_bio_counter_dec" ,"btrfs_clear_skip_qgroup" ,
"btrfs_dio_private_put" ,"btrfs_free_block_rsv" ,"btrfs_free_block_rsv" ,
"btrfs_free_path" ,"btrfs_free_path" ,"btrfs_free_path" ,
"btrfs_put_block_group" ,"btrfs_put_root" ,"btrfs_release_delayed_node" ,
"btrfs_release_path" ,"btrfs_release_path" ,"btrfs_release_path" ,
"btrfs_release_path" ,"btrfs_search_slot" ,"btrfs_tree_read_unlock_blocking" ,
"btrfs_tree_unlock" ,"bus_put" ,"bus_remove_file" ,
"bus_unregister" ,"bus_unregister" ,"cached_dev_put" ,
"caif_disconnect_client" ,"can_put_proto" ,"ceph_free_cap_flush" ,
"ceph_free_lockers" ,"ceph_mdsc_put_request" ,"ceph_mdsc_put_request" ,
"ceph_msg_dump" ,"ceph_put_snap_context" ,"ceph_put_snap_realm" ,
"ceph_put_snap_realm" ,"cfg80211_sinfo_release_content" ,"cgroup_kn_unlock" ,
"cgroup_put" ,"cgroup_threadgroup_change_end" ,"chip_bus_sync_unlock" ,
"cifs_free_hash" ,"cifs_put_writer" ,"class_destroy" ,
"class_unregister" ,"class_unregister" ,"clear_bit" ,
"clear_bit" ,"clear_bit" ,"clear_inode_flag" ,
"clear_inode_flag" ,"clk_bulk_disable" ,"clk_bulk_put" ,
"clk_bulk_put" ,"clk_bulk_unprepare" ,"clk_core_disable_unprepare" ,
"clk_pm_runtime_put" ,"clk_prepare_unlock" ,"clk_propagate_rate_change" ,
"cmd_free" ,"cm_free_msg" ,"cm_free_msg" ,
"complete_all" ,"complete" ,"composite_dev_cleanup" ,
"configfs_put" ,"configfs_unregister_subsystem" ,"config_item_put" ,
"console_unlock" ,"consume_skb" ,"cpu_cache_sysfs_exit" ,
"cpufreq_disable_fast_switch" ,"cpufreq_policy_free" ,"cpuhp_remove_multi_state" ,
"cpuidle_free_state_kobj" ,"cpu_maps_update_done" ,"cpus_read_unlock" ,
"cpus_write_unlock" ,"crypt_dec_pending" ,"crypt_free_tfms" ,
"crypt_free_tfms" ,"crypto_alg_put" ,"crypto_free_shash" ,
"crypto_free_shash" ,"crypto_free_skcipher" ,"crypto_free_sync_skcipher" ,
"crypto_mod_put" ,"css_put" ,"css_put" ,
"cyy_writeb" ,"dax_read_unlock" ,"debugfs_file_put" ,
"debugfs_remove" ,"debugfs_remove" ,"dec_cgroup_namespaces" ,
"del_edac_device_from_global_list" ,"del_edac_pci_from_global_list" ,"destroy_workqueue" ,
"device_del" ,"device_links_write_unlock" ,"device_pm_unlock" ,
"device_remove_file" ,"device_unlock" ,"dev_kfree_skb_any" ,
"dev_kfree_skb_any" ,"devlink_health_reporter_put" ,"devlink_health_reporter_put" ,
"devlink_resources_unregister" ,"devmap_managed_enable_put" ,"devm_kfree" ,
"devm_request_irq" ,"dev_put" ,"dev_put" ,
"dev_put" ,"dev_put" ,"dev_put" ,
"dev_put" ,"dev_put" ,"dev_put" ,
"dev_put" ,"devres_free" ,"devres_release_group" ,
"__dev_status" ,"dir_put_page" ,"disk_put_part" ,
"dlm_end_recovery" ,"dlm_free_lkb" ,"dlm_lock_put" ,
"dlm_lockres_put" ,"dlm_put" ,"dlm_put_lkb" ,
"dlm_release_root_list" ,"dlm_scand_stop" ,"dlm_unlock_recovery" ,
"dlm_unregister_domain_handlers" ,"dma_buf_unmap_attachment" ,"dma_fence_put" ,
"dma_fence_put" ,"dma_fence_put" ,"dma_free_coherent" ,
"dma_free" ,"dma_pool_destroy" ,"dma_resv_list_free" ,
"dma_resv_unlock" ,"dma_unmap_page_attrs" ,"dma_unmap_single_attrs" ,
"dm_bm_unlock" ,"dm_bm_unlock" ,"dm_bufio_unlock" ,
"dm_cache_policy_unregister" ,"dm_exception_table_unlock" ,"dm_exception_table_unlock" ,
"dm_put_device" ,"dm_put" ,"dm_put" ,
"dm_put_live_table" ,"dm_put_live_table" ,"dm_put_target_type" ,
"__dm_resume" ,"dm_table_destroy" ,"dm_table_free_md_mempools" ,
"dm_tm_unlock" ,"dm_uevent_exit" ,"dm_uevent_free" ,
"dm_unlock_md_type" ,"dm_unprepare_ioctl" ,"dmz_unlock_flush" ,
"dmz_unlock_flush" ,"dmz_unlock_map" ,"dmz_unlock_metadata" ,
"dmz_wait_for_free_zones" ,"double_unlock_balance" ,"double_unlock_balance" ,
"double_unlock_hb" ,"down_read" ,"down_read" ,
"down_write" ,"dput" ,"dput" ,
"dput" ,"dquot_free_block" ,"dquot_free_block" ,
"dquot_free_inode" ,"dquot_free_space_nodirty" ,"drm_atomic_state_clear" ,
"drm_atomic_state_put" ,"drm_atomic_state_put" ,"drm_connector_cleanup" ,
"drm_crtc_vblank_put" ,"drm_debugfs_cleanup" ,"drm_dp_mst_topology_put_mstb" ,
"drm_dp_mst_topology_put_port" ,"drm_dp_mst_topology_put_port" ,"drm_framebuffer_put" ,
"drm_gem_object_put_unlocked" ,"drm_gem_object_put_unlocked" ,"drm_gem_shmem_put_pages" ,
"drm_ht_remove" ,"drm_master_put" ,"drm_mode_destroy" ,
"drm_mode_object_unregister" ,"drm_modeset_acquire_fini" ,"drm_modeset_backoff" ,
"drm_modeset_drop_locks" ,"drm_modeset_drop_locks" ,"drm_modeset_unlock" ,
"drm_modeset_unlock" ,"drm_property_blob_put" ,"drm_property_blob_put" ,
"drm_syncobj_put" ,"drv_stop" ,"dst_release" ,
"dst_release" ,"dst_release" ,"e1000e_release_hw_control" ,
"e1000_free_desc_rings" ,"e1000_power_down_phy" ,"eb_vma_array_put" ,
"ecc_free_point" ,"ecryptfs_put_lower_file" ,"edac_debugfs_exit" ,
"edac_mc_sysfs_exit" ,"edac_pci_main_kobj_teardown" ,"edac_subsys_exit" ,
"end_discard" ,"enic_clear_intr_mode" ,"enic_free_vnic_resources" ,
"enic_unset_affinity_hint" ,"evtchn_put" ,"ext4_blkdev_put" ,
"ext4_clear_inode_state" ,"__ext4_journal_stop" ,"ext4_mb_put_buddy_page_lock" ,
"ext4_resize_end" ,"ext4_unlock_group" ,"ext4_write_unlock_xattr" ,
"extent_changeset_free" ,"extent_clear_unlock_delalloc" ,"f2fs_put_dnode" ,
"f2fs_put_page" ,"f2fs_put_page" ,"f2fs_put_page" ,
"f2fs_put_page" ,"f2fs_put_rpages_mapping" ,"f2fs_unlock_all" ,
"f2fs_unlock_op" ,"f2fs_unlock_rpages" ,"fat_free_clusters" ,
"fat_unlock_build_inode" ,"fb_dealloc_cmap" ,"fdp_nci_release_firmware" ,
"fdput" ,"ffs_dev_unlock" ,"ffs_epfiles_destroy" ,
"finish_wait" ,"f_midi_unregister_card" ,"fput" ,
"fput" ,"fput" ,"fput" ,
"fput" ,"fput" ,"fput" ,
"framebuffer_release" ,"free_arenas" ,"free_block_list" ,
"free_buf" ,"__free_buffer_wake" ,"free_buf_info" ,
"free_cell" ,"free_choose_arg_map" ,"free_cpu_cached_iovas" ,
"free_cpumask_var" ,"free_cpumask_var" ,"free_cpumask_var" ,
"free_crush_loc" ,"free_crush_name" ,"free_drawable" ,
"__free_engines" ,"free_extent_map" ,"free_extent_state" ,
"free_extent_state" ,"__free_fdtable" ,"__free_fence_array" ,
"__free_filter" ,"free_idx_lebs" ,"free_iova_fast" ,
"free_ipath" ,"free_map_info" ,"free_mem_extents" ,
"free_module" ,"free_netdev" ,"free_netdev" ,
"free_netdev" ,"free_normalized_path" ,"__free_pages" ,
"free_pages" ,"free_pages" ,"free_pages" ,
"free_percpu" ,"free_percpu" ,"free_perm_bits" ,
"free_pgpath" ,"free_pv_object" ,"free_rsp_buf" ,
"free_rsp_buf" ,"free_sess" ,"free_sess_reqs" ,
"free_tio" ,"free_ud_wq_attr" ,"free_watch_adapter" ,
"fscrypt_fname_free_buffer" ,"fscrypt_free_bounce_page" ,"fs_path_free" ,
"fs_path_free" ,"fs_path_free" ,"fs_put_dax" ,
"fuse_sync_release" ,"fw_device_put" ,"fw_device_put" ,
"fwnode_handle_put" ,"fwnode_handle_put" ,"fwnode_handle_put" ,
"gameport_free_port" ,"genlmsg_cancel" ,"genlmsg_cancel" ,
"genl_unlock" ,"genl_unlock_all" ,"genl_unregister_family" ,
"gf128mul_free_64k" ,"gfs2_glock_dq_uninit" ,"gfs2_qa_put" ,
"gfs2_trans_end" ,"gnttab_request_free_callback" ,"gnttab_set_unmap_op" ,
"gpiod_put" ,"graph_unlock" ,"gserial_free_port" ,
"gsmi_buf_free" ,"gss_put_ctx" ,"gve_adminq_free" ,
"gve_free_counter_array" ,"gve_free_notify_blocks" ,"gve_free_queue_page_list" ,
"gve_tx_free_rings" ,"__hash_remove" ,"hci_conn_drop" ,
"hci_conn_del" ,"hci_dev_put" ,"hci_dev_put" ,
"hci_dev_unlock" ,"hci_free_dev" ,"hci_unregister_cb" ,
"hfsplus_find_exit" ,"hid_device_io_stop" ,"hlist_bl_unlock" ,
"hlist_bl_unlock" ,"hpsa_free_cmd_pool" ,"hpsa_free_ioaccel1_cmd_and_bft" ,
"hpsa_free_ioaccel2_cmd_and_bft" ,"hpsa_free_ioaccel2_cmd_and_bft" ,"hpsa_free_reply_queues" ,
"hpsa_free_sas_node" ,"hpsa_free_sas_port" ,"htab_unlock_bucket" ,
"hwsim_unregister_virtio_driver" ,"i2c_put_adapter" ,"i915_active_release" ,
"i915_audio_component_put_power" ,"i915_block_free" ,"i915_gem_context_unlock_engines" ,
"i915_gem_object_create_internal" ,"i915_gem_object_put" ,"i915_gem_object_unlock" ,
"i915_gem_object_unlock" ,"ibdev_dbg" ,"ibdev_dbg" ,
"ib_device_put" ,"ib_device_put" ,"ib_device_put" ,
"ib_device_put" ,"ib_device_unregister_rdmacg" ,"ibdev_put_vector" ,
"ib_dma_unmap_sg" ,"ib_dma_unmap_single" ,"ib_dma_unmap_single" ,
"ib_free_cq" ,"ib_mr_pool_put" ,"ib_sa_client_put" ,
"ib_sa_unregister_client" ,"ib_unregister_client" ,"ib_unregister_mad_agent" ,
"idr_destroy" ,"idr_preload_end" ,"idr_remove" ,
"ieee802154_free_hw" ,"iget_failed" ,"i_mmap_unlock_read" ,
"in6_dev_put" ,"inet_diag_unlock_handler" ,"inet_free_ifa" ,
"inet_putpeer" ,"INIT_LIST_HEAD" ,"inode_unlock" ,
"inode_unlock" ,"inode_unlock" ,"inode_unlock" ,
"inode_unlock_shared" ,"input_close_device" ,"input_free_device" ,
"input_mt_new_trkid" ,"input_proc_exit" ,"instance_put" ,
"intel_backlight_device_unregister" ,"intel_context_unlock_pinned" ,"intel_de_write_fw" ,
"intel_display_power_put_async" ,"intel_display_power_put" ,"intel_dsb_disable_engine" ,
"intel_engine_pm_put_async" ,"intel_engine_pm_put" ,"intel_engine_pm_put" ,
"intel_frontbuffer_put" ,"intel_gt_pm_put" ,"intel_runtime_pm_put" ,
"intel_runtime_pm_put" ,"intel_runtime_pm_put_raw" ,"intel_tc_port_unlock" ,
"intel_uncore_forcewake_put" ,"io_ctl_unmap_page" ,"io_mem_free" ,
"iommu_detach_device" ,"iommu_group_put" ,"iommu_group_put" ,
"io_ring_submit_unlock" ,"iounmap" ,"iounmap" ,
"ipoib_cm_free_rx_ring" ,"ipoib_neigh_free" ,"ipoib_neigh_put" ,
"ipoib_unregister_debugfs" ,"ip_set_free" ,"ip_set_put_byindex" ,
"ip_set_type_unlock" ,"iput" ,"iput" ,
"iput" ,"iput" ,"iput" ,
"iput" ,"iput" ,"iput" ,
"ip_vs_scheduler_put" ,"ip_vs_use_count_dec" ,"irq_domain_free_fwnode" ,
"irq_put_desc_busunlock" ,"irq_put_desc_unlock" ,"irq_unlock_sparse" ,
"iscsi_host_free" ,"iscsi_pool_free" ,"iser_conn_release" ,
"is_namespace_blk" ,"j1939_priv_put" ,"j1939_session_put" ,
"j1939_session_put" ,"jbd_unlock_bh_journal_head" ,"journal_end" ,
"journal_free_journal_head" ,"kcmp_unlock" ,"kcov_remote_stop" ,
"kernel_param_unlock" ,"kernfs_put_active" ,"kernfs_put" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree_skb" ,
"kfree_skb" ,"kfree_skb" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kfree" ,"kfree" ,"kfree" ,
"kmem_cache_destroy" ,"kmem_cache_free" ,"kmem_cache_free" ,
"kmem_cache_free" ,"kmem_cache_free" ,"kmem_cache_free" ,
"kmem_free" ,"kmem_free" ,"kmem_free" ,
"kobject_put" ,"kobject_put" ,"kobject_put" ,
"kobject_put" ,"kref_put" ,"kref_put" ,
"kset_unregister" ,"kunmap" ,"kunmap" ,
"kvfree" ,"kvfree" ,"kvfree" ,
"kvfree" ,"kvfree" ,"kvfree" ,
"kvfree" ,"kvfree" ,"kvfree" ,
"kvfree" ,"kvfree" ,"kvfree" ,
"kvfree" ,"kvfree" ,"kzfree" ,
"kzfree" ,"l1oip_4bit_free" ,"l2cap_chan_unlock" ,
"leb_write_unlock" ,"leb_write_unlock" ,"list_del" ,
"list_del" ,"local_bh_enable" ,"lockd_down" ,
"lock_release" ,"locks_free_lock" ,"lwtstate_put" ,
"macsec_rxsc_put" ,"md_bitmap_file_unmap" ,"mddev_unlock" ,
"mdiobus_unregister_device" ,"media_device_unregister_entity" ,"media_device_unregister_entity" ,
"media_entity_cleanup" ,"__media_entity_remove_link" ,"media_entity_remove_links" ,
"media_request_put" ,"memcg_put_cache_ids" ,"__mem_cgroup_free" ,
"mem_cgroup_id_put" ,"mempool_free" ,"memunmap" ,
"memzero_explicit" ,"mesh_table_free" ,"mgmt_cmd_complete" ,
"mgmt_cmd_complete" ,"mgmt_cmd_status" ,"mgmt_cmd_status" ,
"migrate_read_unlock" ,"misc_deregister" ,"mkiss_put" ,
"mlx4_bitmap_free" ,"mlx4_buddy_free" ,"mlx4_counter_free" ,
"mlx4_cq_free_icm" ,"mlx4_cq_free" ,"mlx4_db_free" ,
"mlx4_ib_free_eqs" ,"mlx4_mpt_free_icm" ,"mlx4_mr_hw_put_mpt" ,
"mlx4_pci_disable_device" ,"mlx4_pd_free" ,"mlx4_pd_free" ,
"mlx4_pd_free" ,"mlx4_qp_free" ,"mlx4_release_resource" ,
"mlx4_srq_free_icm" ,"mlx4_uar_free" ,"mlx4_uar_free" ,
"mlx4_unregister_mac" ,"mlx4_xrcd_free" ,"mmap_read_unlock" ,
"mmap_read_unlock" ,"mmap_read_unlock" ,"mmap_write_unlock" ,
"mmap_write_unlock" ,"mm_pkey_free" ,"mnt_drop_write_file" ,
"mntput" ,"mod_kobject_put" ,"module_memfree" ,
"module_put" ,"module_put" ,"module_put" ,
"module_put" ,"module_put" ,"mpi_free" ,
"mpol_cond_put" ,"mutex_destroy" ,"mutex_unlock" ,
"mutex_unlock" ,"mutex_unlock" ,"mutex_unlock" ,
"mutex_unlock" ,"mutex_unlock" ,"mutex_unlock" ,
"mutex_unlock" ,"mutex_unlock" ,"mutex_unlock" ,
"mutex_unlock" ,"mutex_unlock" ,"mutex_unlock" ,
"mutex_unlock" ,"namespace_unlock" ,"netdev_name_node_free" ,
"netif_addr_unlock_bh" ,"netif_tx_unlock_bh" ,"netlink_kernel_release" ,
"netlink_unlock_table" ,"netlink_unregister_notifier" ,"netpoll_poll_unlock" ,
"nf_conntrack_unregister_notifier" ,"nfc_put_device" ,"nf_ct_unexpect_related" ,
"nfnetlink_set_err" ,"nfnetlink_subsys_unregister" ,"nfnl_unlock" ,
"nfnl_unlock" ,"nfs4_free_createdata" ,"nfs4_label_free" ,
"nfs4_put_state_owner" ,"nfs4_put_stid" ,"nfs4_put_stid" ,
"nfsd_file_put" ,"nfserrno" ,"nfs_free_fattr" ,
"nfs_free_fattr" ,"nfs_free_fhandle" ,"nfs_list_remove_request" ,
"nfs_put_client" ,"nfs_readpage_release" ,"nft_unregister_expr" ,
"nf_unregister_sockopt" ,"nla_nest_cancel" ,"nla_nest_cancel" ,
"nla_nest_end" ,"nla_put_flag" ,"nla_put_u32" ,
"nlmsg_cancel" ,"nlmsg_free" ,"nlmsg_free" ,
"nlmsg_free" ,"nlmsg_free" ,"nlmsvc_release_block" ,
"nr_node_put" ,"ntfs_index_ctx_put" ,"nvdimm_bus_unlock" ,
"nvdimm_put_key" ,"nvdimm_put_key" ,"nvme_dev_unmap" ,
"nvme_disable_streams" ,"nvme_fc_ctrl_put" ,"nvme_fc_lport_put" ,
"nvme_fc_rport_put" ,"nvme_put_subsystem" ,"nvme_rdma_free_io_queues" ,
"nvme_rdma_free_qe" ,"nvme_rdma_free_queue" ,"nvme_tcp_free_admin_queue" ,
"nvme_tcp_free_io_queues" ,"nvmet_fc_tgtport_put" ,"nvmet_req_complete" ,
"nvmet_req_complete" ,"nvmet_req_complete" ,"__nvmet_req_complete" ,
"nvmet_subsys_put" ,"nv_stop_rxtx" ,"o2net_complete_nsw" ,
"o2net_set_advance_stop_time" ,"o2net_unregister_hb_callbacks" ,"o2nm_node_put" ,
"o2nm_node_put" ,"o2nm_unlock_subsystem" ,"ocfs2_free_alloc_context" ,
"ocfs2_free_alloc_context" ,"ocfs2_free_alloc_context" ,"ocfs2_free_alloc_context" ,
"ocfs2_free_alloc_context" ,"ocfs2_free_alloc_context" ,"ocfs2_free_alloc_context" ,
"ocfs2_free_alloc_context" ,"ocfs2_free_dir_lookup_result" ,"ocfs2_free_path" ,
"ocfs2_free_quota_recovery" ,"ocfs2_inode_unlock" ,"ocfs2_inode_unlock" ,
"ocfs2_inode_unlock" ,"ocfs2_refcount_tree_put" ,"ocfs2_reflink_inodes_unlock" ,
"ocfs2_run_deallocs" ,"ocfs2_stack_driver_put" ,"ocfs2_unlock_global_qf" ,
"ocfs2_unlock_refcount_tree" ,"ocfs2_xattr_bucket_free" ,"option_rezero" ,
"ovs_unlock" ,"p9_req_put" ,"page_ref_sub" ,
"path_put" ,"path_put" ,"pci_config_pm_runtime_put" ,
"pci_dev_put" ,"pci_dev_put" ,"pci_dev_put" ,
"pci_dev_unlock" ,"pci_disable_device" ,"pci_disable_device" ,
"pci_disable_msi" ,"pci_disable_msi" ,"pci_disable_msix" ,
"pci_disable_pcie_error_reporting" ,"pci_iounmap" ,"pci_remove_resource_files" ,
"pcistub_device_put" ,"pci_unlock_rescan_remove" ,"pci_unmap_rom" ,
"pde_free" ,"percpu_up_write" ,"perf_ctx_unlock" ,
"perf_ctx_unlock" ,"perf_pmu_enable" ,"phonet_proto_put" ,
"phy_pm_runtime_put" ,"phy_pm_runtime_put_sync" ,"ping_clear_saddr" ,
"pipe_unlock" ,"__pipe_unlock" ,"pipe_unlock" ,
"platform_device_unregister" ,"platform_driver_unregister" ,"platform_driver_unregister" ,
"plt_clk_unregister_fixed_rate_loop" ,"pm_autosleep_unlock" ,"pmd_write_unlock" ,
"pm_runtime_disable" ,"pm_runtime_mark_last_busy" ,"pm_runtime_put_autosuspend" ,
"pm_runtime_put_noidle" ,"pm_runtime_put_noidle" ,"pm_runtime_put" ,
"pm_runtime_put" ,"pm_runtime_put_sync" ,"pm_runtime_put_sync_suspend" ,
"pm_runtime_set_suspended" ,"posix_acl_release" ,"pps_unlock" ,
"proc_free_inum" ,"property_entries_free" ,"proto_unregister" ,
"push" ,"put_anon_vma" ,"put_busid_priv" ,
"put_clock_desc" ,"put_cred" ,"put_cred" ,
"put_cred" ,"put_css_set" ,"put_device" ,
"put_device" ,"put_device" ,"put_device" ,
"put_device" ,"put_device" ,"put_device" ,
"put_dev_pagemap" ,"put_disk" ,"put_files_struct" ,
"put_filesystem" ,"put_futex_key" ,"put_ipc_ns" ,
"put_journal_list" ,"__put_lkb" ,"put_net" ,
"put_net" ,"put_net" ,"put_online_cpus" ,
"put_online_mems" ,"put_page" ,"put_page" ,
"put_page" ,"put_page" ,"put_page" ,
"put_page" ,"put_page" ,"put_page" ,
"put_page" ,"put_page" ,"put_page" ,
"put_pfn" ,"put_pid_ns" ,"put_pipe_version" ,
"put_res" ,"put_rng" ,"put_rsb" ,
"__put_seccomp_filter" ,"put_space" ,"put_swap_device" ,
"put_swap_page" ,"__put_system" ,"put_task_struct" ,
"put_task_struct" ,"put_task_struct" ,"put_task_struct" ,
"put_task_struct" ,"put_task_struct" ,"put_tei_msg" ,
"put_tty_driver" ,"put_unused_fd" ,"put_unused_fd" ,
"put_unused_fd" ,"put_vaddr_frames" ,"put_workspace" ,
"pvcalls_back_release_active" ,"qat_alg_free_bufl" ,"qat_crypto_put_instance" ,
"qat_rsa_clear_ctx" ,"qdisc_bstats_update" ,"qdisc_put" ,
"queued_spin_unlock" ,"queue_unlock" ,"queue_unlock" ,
"__quota_error" ,"raid5_release_stripe" ,"_raw_read_unlock_bh" ,
"_raw_read_unlock" ,"_raw_read_unlock" ,"_raw_spin_unlock_bh" ,
"_raw_spin_unlock_irq" ,"_raw_spin_unlock_irq" ,"_raw_spin_unlock" ,
"_raw_spin_unlock" ,"_raw_write_unlock_bh" ,"_raw_write_unlock_irq" ,
"_raw_write_unlock" ,"rcu_read_lock" ,"rcu_read_unlock_bh" ,
"rcu_read_unlock_bh" ,"rcu_read_unlock" ,"rcu_read_unlock" ,
"rcu_read_unlock" ,"rcu_read_unlock" ,"rcu_read_unlock" ,
"rcu_read_unlock" ,"rdma_lookup_put_uobject" ,"rdma_restrack_put" ,
"rdma_rw_unmap_sg" ,"rdma_unfill_sgid_attr" ,"rds_ib_dev_put" ,
"rds_ib_dev_put" ,"rds_tcp_conn_free" ,"regmap_debugfs_exit" ,
"regulator_bulk_unregister_supply_alias" ,"reiserfs_free_bitmap_cache" ,"reiserfs_write_unlock" ,
"release_firmware" ,"release_metapage" ,"release_metapage" ,
"release_metapath" ,"__release_region" ,"release_sock" ,
"release_sock" ,"release_sock" ,"release_sock" ,
"remove_proc_entry" ,"remove_proc_entry" ,"remove_proc_entry" ,
"remove_wait_queue" ,"rhashtable_walk_stop" ,"ring_buffer_free" ,
"ring_buffer_put" ,"__rmi_unregister_function_handlers" ,"rmw_clear_fw" ,
"rpc_cb_add_xprt_release" ,"rpc_clnt_debugfs_unregister" ,"rpc_unregister_client" ,
"rt_fibinfo_free_cpus" ,"rtnl_link_unregister" ,"__rtnl_unlock" ,
"rtnl_unlock" ,"rtnl_unlock" ,"rtrs_iu_free" ,
"rvt_free_rq" ,"rvt_put_mr" ,"sas_port_free" ,
"sas_unregister_ports" ,"sb_end_pagefault" ,"sbp2_unmap_scatterlist" ,
"scsi_autopm_put_target" ,"scsi_device_put" ,"scsi_eh_restore_cmnd" ,
"scsi_host_put" ,"scsi_host_put" ,"scsi_log_release_buffer" ,
"sdata_unlock" ,"sdw_release_bus_lock" ,"send_settings_rsp" ,
"serial8250_rpm_put" ,"sess_free_buffer" ,"sg_free_table_chained" ,
"sg_free_table" ,"sg_free_table" ,"siw_cm_free_work" ,
"skb_queue_head" ,"skcipher_request_free" ,"skcipher_request_free" ,
"skcipher_unmap_dst" ,"sk_free" ,"sk_psock_put" ,
"SMB2_sess_free_buffer" ,"smbd_disconnect_rdma_connection" ,"smc_ism_put_vlan" ,
"smc_wr_tx_put_slot" ,"snd_hda_codec_pcm_put" ,"snd_hdac_power_down_pm" ,
"snd_hdac_power_down" ,"snd_info_free_entry" ,"snd_media_stop_pipeline" ,
"snd_pcm_stream_unlock_irqrestore" ,"snd_pcm_stream_unlock_irq" ,"sock_kfree_s" ,
"sock_put" ,"sock_put" ,"sock_put" ,
"sock_release" ,"sock_release" ,"sock_release" ,
"sock_release" ,"spi_dev_put" ,"spi_dev_put" ,
"spin_unlock" ,"spin_unlock_bh" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock_irqrestore" ,"spin_unlock_irqrestore" ,"spin_unlock_irq" ,
"spin_unlock_irq" ,"spin_unlock_irq" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spin_unlock" ,
"spin_unlock" ,"spin_unlock" ,"spi_set_cs" ,
"sp_put" ,"squashfs_cache_put" ,"squashfs_cache_put" ,
"srcu_read_unlock" ,"sta_info_free" ,"strcmp" ,
"strlcpy" ,"strncmp" ,"stub_device_free" ,
"subdev_fh_free" ,"svc_rdma_send_ctxt_put" ,"svc_stop_kthreads" ,
"__symbol_put" ,"sysfs_remove_file" ,"sysfs_remove_group" ,
"sysfs_remove_group" ,"sysfs_remove_link" ,"sysfs_streq" ,
"task_rq_unlock" ,"task_rq_unlock" ,"task_unlock" ,
"tb_ring_stop" ,"tb_tunnel_free" ,"tb_tunnel_free" ,
"tb_tunnel_free" ,"teardown_sgtable" ,"thermal_cooling_device_unregister" ,
"tipc_bcast_unlock" ,"tipc_node_read_unlock" ,"tipc_node_write_unlock_fast" ,
"tls_sw_release_resources_rx" ,"tpm_buf_destroy" ,"tpm_put_ops" ,
"tpm_put_ops" ,"trace_array_put" ,"__trace_array_put" ,
"trace_array_put" ,"tracefs_remove" ,"trace_i915_request_wait_end" ,
"trace_mm_compaction_end" ,"trace_nfs4_unlock" ,"trace_ocfs2_get_dentry_end" ,
"trace_ocfs2_iget_end" ,"trace_ocfs2_query_inode_wipe_end" ,"trace_ocfs2_queue_orphan_scan_end" ,
"trace_parser_put" ,"trace_suspend_resume" ,"trace_xdp_exception" ,
"trace_xfs_free_extent" ,"trace_xfs_rmap_unmap_error" ,"transport_class_unregister" ,
"transport_destroy_device" ,"ttm_bo_unreserve" ,"ttm_mem_global_free" ,
"ttm_mem_io_unlock" ,"ttm_pool_update_free_locked" ,"ttm_write_unlock" ,
"tty_free_file" ,"tty_kref_put" ,"tty_ldisc_deref" ,
"tty_unlock" ,"tty_unregister_device" ,"tty_unregister_ldisc" ,
"tty_write_unlock" ,"tun_put" ,"u64_stats_update_end" ,
"ubi_dump_vid_hdr" ,"ubi_err" ,"ubi_err" ,
"ubi_err" ,"ubi_err" ,"ubi_err" ,
"ubi_free_vid_buf" ,"ubifs_err" ,"ubifs_err" ,
"ubifs_release_budget" ,"ubifs_release_budget" ,"ubifs_release_lprops" ,
"ubi_put_device" ,"ubi_wl_put_peb" ,"udp_tunnel_sock_release" ,
"ulist_free" ,"__unbind_from_irq" ,"unix_state_double_unlock" ,
"unix_sysctl_unregister" ,"unlock_ablock" ,"unlock_buffer" ,
"unlock_cluster_or_swap_info" ,"unlock_device_hotplug" ,"unlock_dir" ,
"unlock_extent_cached" ,"unlock_extent" ,"unlock_fat" ,
"unlock_fs" ,"unlock_journal" ,"unlock_mount_hash" ,
"unlock_page" ,"unlock_page" ,"unlock_page" ,
"unlock_page" ,"unlock_page" ,"unlock_page_memcg" ,
"unlock_page" ,"unlock_page" ,"unlock_rdev" ,
"unlock_rsb" ,"unlock_system_sleep" ,"unlock_two_nondirectories" ,
"unmap_mft_record" ,"unmap_mft_record" ,"unregister_blkdev" ,
"unregister_chrdev_region" ,"unregister_chrdev_region" ,"unregister_chrdev" ,
"unregister_device" ,"unregister_filesystem" ,"unregister_inet6addr_notifier" ,
"unregister_inet6addr_validator_notifier" ,"unregister_inetaddr_notifier" ,"unregister_inetaddr_validator_notifier" ,
"unregister_netdevice_notifier" ,"unregister_netdev" ,"unregister_net_sysctl_table" ,
"unregister_pernet_device" ,"unregister_pernet_device" ,"unregister_pernet_subsys" ,
"unregister_pernet_subsys" ,"unregister_reboot_notifier" ,"unregister_shrinker" ,
"unregister_sysctl_table" ,"unregister_trace_sched_wakeup" ,"unset_reloc_control" ,
"up" ,"up" ,"up" ,
"up_read" ,"up_read" ,"up_write" ,
"up_write" ,"urb_free_priv" ,"usb_autopm_put_interface_async" ,
"usb_autopm_put_interface" ,"usb_autosuspend_device" ,"usb_ep_dequeue" ,
"usb_ep_free_request" ,"usb_free_coherent" ,"usb_free_urb" ,
"usbfs_decrease_memory_usage" ,"usb_hcd_giveback_urb" ,"usb_hcd_pci_remove" ,
"usb_hcd_unlink_urb_from_ep" ,"usb_put_hcd" ,"usb_put_hcd" ,
"usb_put_intf" ,"usb_release_bos_descriptor" ,"usb_remove_hcd" ,
"usb_unanchor_urb" ,"usb_unlocked_enable_lpm" ,"user_path_at" ,
"usnic_vnic_put_resources" ,"v4l2_device_unregister" ,"v4l2_device_unregister" ,
"v4l2_fh_del" ,"v4l2_fh_exit" ,"v4l2_m2m_release" ,
"v9fs_cache_unregister" ,"__vb2_cleanup_fileio" ,"vema_unregister" ,
"verbose" ,"vfio_device_put" ,"vfio_group_put" ,
"vfree" ,"vfree" ,"__vfree" ,
"vfree" ,"vfree" ,"vfree" ,
"vhost_vsock_free" ,"video_unregister_device" ,"video_unregister_device" ,
"virtio_gpu_array_unlock_resv" ,"virtio_transport_free_pkt" ,"virtio_transport_put_credit" ,
"vlv_punit_put" ,"vma_put_pages" ,"vm_area_free" ,
"vm_free_page" ,"vmw_cmdbuf_cur_unlock" ,"vmw_fifo_resource_dec" ,
"vnic_wq_free" ,"vunmap" ,"__wake_up" ,
"wc_unlock" ,"wdev_unlock" ,"wpan_phy_unregister" ,
"writel" ,"writel" ,"write_seqcount_end" ,
"write_sequnlock_bh" ,"write_sequnlock" ,"x25_neigh_put" ,
"x25_route_put" ,"xenbus_dev_fatal" ,"xenbus_dev_fatal" ,
"xenbus_dev_fatal" ,"xenbus_free_evtchn" ,"xen_snd_front_evtchnl_free_all" ,
"xenvif_deinit_hash" ,"xenvif_disconnect_ctrl" ,"xfrm_state_put" ,
"xfrm_unregister_type" ,"xfs_blkdev_put" ,"xfs_blkdev_put" ,
"xfs_da_state_free" ,"xfs_dqunlock" ,"xfs_dqunlock" ,
"xfs_dqunlock" ,"xfs_iunlock" ,"xfs_iunlock" ,
"xfs_iunlock" ,"xfs_iunlock" ,"xfs_iunlock" ,
"xfs_iunlock" ,"xfs_iunlock" ,"xfs_perag_put" ,
"xfs_perag_put" ,"xfs_qm_dqput" ,"xfs_sysctl_unregister" ,
"xfs_trans_cancel" ,"xhci_dbg_trace" ,"xhci_free_command" ,
"xhci_free_command" ,"xhci_free_command" ,"xhci_ring_free" ,
"xhci_segment_free" ,"xp_dma_unmap" ,"xprt_clear_locked" ,
"xprt_free_allocation" ,"xprt_put" ,"xprt_switch_put" ,
"xt_free_table_info" ,"xt_percpu_counter_free" };
std::string pair_fncs[DATABASE_SIZE] = {
"acpi_bus_register_driver","acpi_enable_wakeup_device_power","acpi_ec_start",
"acpi_evaluate_integer","acpi_evaluate_object","acpi_os_allocate",
"acpi_os_allocate_zeroed","acpi_os_acquire_lock","acpi_os_unmap_memory",
"acpi_processor_register_performance","acpi_get_table","acpi_lock_hp_context",
"acpi_map_cpu","acpi_ut_acquire_mutex","acpi_ex_resolve_operands",
"acpi_ut_create_internal_object_dbg","acpi_ut_evaluate_object","afs_get_call",
"afs_get_cell","afs_get_writeback_key","agp_allocate_memory_wrap",
"ahci_rpm_get_port","ata_host_get","atomic64_add",
"atomic_inc","atomic_set","atomic_dec",
"atomic_fetch_inc","atomic_inc","atomic_inc_not_zero",
"atomic_inc_return","to_siw_dev","atomic_inc",
"atomic_long_add_return","atomic_add","atomic_add_return",
"kzalloc","batadv_gw_get_selected_gw_node","batadv_gw_node_get",
"batadv_hardif_neigh_get","batadv_hardif_get_by_netdev","batadv_netlink_get_ifindex",
"batadv_primary_if_get_selected","batadv_softif_create","dev_get_by_index",
"kref_get","batadv_neigh_ifinfo_get","batadv_orig_router_get",
"batadv_neigh_ifinfo_get","batadv_orig_router_get","batadv_gw_get_selected_orig",
"batadv_neigh_node_get_or_create","batadv_orig_hash_find","batadv_orig_router_get",
"batadv_softif_vlan_get","kthread_create_on_node","bdi_get",
"bdi_get_by_id","bdget_disk","blk_trace_get_queue",
"_binder_inner_proc_lock","_binder_proc_lock","binder_get_node",
"bio_alloc","bio_alloc_bioset","bio_associate_blkg",
"bitmap_zalloc","blkdev_get","blk_start_plug",
"blk_mq_alloc_tag_set","blk_mq_freeze_queue","blktrans_dev_get",
"kzalloc","__alloc_percpu_gfp","bpf_cgroup_storage_alloc",
"bpf_cgroup_storage_alloc","bpf_prog_clone_create","bpf_prog_alloc",
"bpf_prog_add","kzalloc","brelse",
"d_inode","ext4_get_inode_loc","ocfs2_find_leaf",
"ocfs2_read_extent_block","ocfs2_read_inode_block","kzalloc",
"btf_type_by_id","btree_node_alloc_replacement","btrfs_backref_alloc_edge",
"btrfs_backref_iter_alloc","btrfs_bio_counter_inc_blocked","btrfs_set_skip_qgroup",
"btrfs_create_dio_private","btrfs_alloc_block_rsv","btrfs_alloc_path",
"alloc_path_for_send","btrfs_alloc_path","fs_path_alloc",
"btrfs_create_block_group_cache","btrfs_get_fs_root","btrfs_get_delayed_node",
"btrfs_alloc_path","btrfs_get_fs_root","btrfs_item_key_to_cpu",
"btrfs_release_path","btrfs_search_slot","btrfs_tree_read_lock",
"btrfs_alloc_tree_block","bus_get","bus_create_file",
"bus_register","register_chrdev","cached_dev_get",
"caif_connect_client","can_get_proto","ceph_alloc_cap_flush",
"kcalloc","ceph_mdsc_get_request","lookup_get_request",
"printk","ceph_get_snap_context","ceph_get_snap_realm",
"get_quota_realm","rdev_get_station","cgroup_kn_lock_live",
"cgroup_get","cgroup_threadgroup_change_begin","chip_bus_lock",
"cifs_alloc_hash","cifs_get_writer","__class_create",
"bus_register","__class_register","test_and_clear_bit",
"test_and_set_bit","test_bit","set_acl_inode",
"set_inode_flag","clk_enable","clk_get",
"of_clk_get","clk_prepare","clk_core_prepare_enable",
"clk_pm_runtime_get","clk_prepare_lock","clk_propagate_rate_change",
"fill_cmd","cm_alloc_msg","cm_alloc_response_msg",
"set_trace_device","__init_completion","composite_dev_prepare",
"configfs_get","configfs_register_subsystem","configfs_get_config_item",
"console_lock","consume_skb","cpu_cache_sysfs_init",
"cpufreq_enable_fast_switch","cpufreq_add_policy_cpu","trace_create_savedcmd",
"kzalloc","cpu_maps_update_begin","cpus_read_lock",
"cpus_write_lock","crypt_inc_pending","kcalloc",
"kmalloc","crypto_stats_get","crypto_alloc_shash",
"kmalloc","crypto_alloc_skcipher","context_v2_alloc_cipher",
"crypto_mod_get","css_get","get_mem_cgroup_from_mm",
"writeb","dax_read_lock","debugfs_file_get",
"debugfs_create_dir","debugfs_create_file","inc_cgroup_namespaces",
"add_edac_dev_to_global_list","add_edac_pci_to_global_list","alloc_workqueue",
"device_add","device_links_write_lock","device_pm_lock",
"sony_set_device_id","device_lock","dev_kfree_skb_any",
"netdev_alloc_skb_ip_align","devlink_health_reporter_get_from_cb","devlink_health_reporter_get_from_info",
"nsim_dev_resources_register","devmap_managed_enable_get","devm_kzalloc",
"devm_request_irq","batadv_hardif_get_by_netdev","dev_get_by_index",
"dev_get_by_name","dev_hold","ieee802154_nl_get_dev",
"in6_dev_get","rose_dev_get","rxe_get_dev_from_net",
"wimax_dev_get_by_genl_info","__devres_alloc_node","devres_open_group",
"find_device","dir_get_page","disk_get_part",
"dlm_begin_recovery","dlm_allocate_lkb","dlm_lock_get",
"dlm_lockres_get","dlm_grab","find_lkb",
"dlm_create_root_list","dlm_scand_start","dlm_lock_recovery",
"dlm_register_domain_handlers","dma_buf_map_attachment","dma_fence_get",
"dma_fence_get_rcu","sync_file_get_fence","dma_alloc_coherent",
"dma_alloc","dma_pool_create","dma_resv_list_alloc",
"drm_vma_node_start","dma_map_page_attrs","dma_map_single_attrs",
"dm_block_data","dm_bm_read_lock","dm_bufio_lock",
"dm_cache_policy_register","dm_exception_table_lock","dm_exception_table_lock_init",
"dm_get_device","dm_table_create","get_result_buffer",
"dm_dax_get_live_target","dm_get_live_table","dm_get_target_type",
"dm_suspended_md","dm_table_create","dm_table_get_md_mempools",
"dm_tm_shadow_block","dm_uevent_init","dm_uevent_alloc",
"dm_lock_md_type","dm_prepare_ioctl","dmz_lock_flush",
"dmz_lock_map","dmz_lock_map","dmz_lock_metadata",
"dmz_alloc_zone","find_lock_later_rq","find_lock_lowest_rq",
"double_lock_hb","down_read","up_read",
"lookup_create_osd","dget","dget_parent",
"PTR_ERR","dquot_alloc_block","dquot_alloc_block_nofail",
"dquot_alloc_inode","dquot_alloc_space_nodirty","drm_atomic_state_alloc",
"drm_atomic_get_crtc_state","drm_atomic_state_alloc","drm_connector_init",
"drm_crtc_vblank_get","drm_debugfs_init","drm_dp_mst_topology_get_mstb_validated",
"drm_dp_get_port","drm_dp_mst_topology_get_port_validated","drm_framebuffer_lookup",
"drm_gem_object_lookup","drm_vma_offset_exact_lookup_locked","drm_gem_shmem_get_pages",
"drm_ht_create","drm_master_create","drm_mode_duplicate",
"drm_mode_object_add","drm_modeset_acquire_init","drm_modeset_acquire_init",
"drm_modeset_acquire_init","drm_modeset_lock","drm_modeset_lock",
"mutex_lock_nested","drm_property_create_blob","drm_property_lookup_blob",
"drm_syncobj_get","drv_start","dst_cache_get",
"ipv6_dev_get_saddr","sk_dst_get","e1000e_get_hw_control",
"kcalloc","e1000e_power_up_phy","eb_vma_array_create",
"ecc_alloc_point","ecryptfs_get_lower_file","edac_debugfs_init",
"edac_mc_sysfs_init","edac_pci_main_kobj_setup","edac_subsys_init",
"begin_discard","enic_set_intr_mode","enic_alloc_vnic_resources",
"enic_set_affinity_hint","evtchn_get","ext4_blkdev_get",
"ext4_xattr_ibody_inline_set","__ext4_journal_start","ext4_mb_get_buddy_page_lock",
"ext4_resize_begin","ext4_lock_group","ext4_write_lock_xattr",
"btrfs_delalloc_reserve_space","unlock_extent","f2fs_get_dnode_of_data",
"f2fs_get_node_page","f2fs_grab_cache_page","get_checkpoint_version",
"get_seg_entry","f2fs_pagecache_get_page","f2fs_lock_all",
"f2fs_lock_op","f2fs_cluster_blocks","fat_alloc_clusters",
"fat_lock_build_inode","fb_alloc_cmap_gfp","fdp_nci_get_versions",
"fdget","ffs_dev_lock","ffs_sb_create_file",
"prepare_to_wait","f_midi_register_card","fget",
"get_file","get_mm_exe_file","__get_unused_fd_flags",
"nbd_get_socket","sctp_getsockopt_peeloff_common","sockfd_lookup",
"framebuffer_alloc","alloc_arena","btrfs_alloc_path",
"alloc_buf","__alloc_buffer_wait","cfv_alloc_and_copy_to_shm",
"alloc_cell","alloc_choose_arg_map","alloc_iova",
"alloc_cpumask_var","zalloc_cpumask_var","zalloc_cpumask_var_node",
"alloc_crush_loc","alloc_crush_name","alloc_drawable",
"alloc_engines","alloc_extent_map","alloc_extent_state",
"btrfs_split_delalloc_extent","alloc_fdtable","kvmalloc_array",
"kzalloc","alloc_idx_lebs","intel_alloc_iova",
"btrfs_alloc_path","kmalloc","kzalloc",
"kmalloc","alloc_netdev_mqs","netdev_priv",
"register_netdev","get_normalized_path","alloc_pages",
"__get_free_pages","get_zeroed_page","vmalloc",
"__alloc_percpu","__alloc_percpu_gfp","kzalloc",
"alloc_pgpath","kcalloc","cifs_send_recv",
"compound_send_recv","kzalloc_node","ib_alloc_mr",
"alloc_tio","kzalloc_node","alloc_watch_adapter",
"fscrypt_fname_alloc_buffer","fscrypt_alloc_bounce_page","alloc_path_for_send",
"fs_path_alloc","fs_path_alloc_reversed","fs_dax_get_by_bdev",
"fuse_iget","fw_device_get","fw_device_get_by_devt",
"fwnode_graph_get_port_parent","fwnode_graph_get_remote_endpoint","fwnode_graph_get_remote_port_parent",
"gameport_allocate_port","genlmsg_put","nla_put_u32",
"genl_lock","genl_lock_all","genl_register_family",
"kzalloc","gfs2_glock_nq_init","gfs2_qa_get",
"gfs2_trans_begin","gnttab_alloc_grant_references","gnttab_set_map_op",
"gpiod_get_optional","graph_lock","gs_port_alloc",
"gsmi_buf_alloc","gss_cred_get_ctx","gve_adminq_alloc",
"gve_alloc_counter_array","gve_alloc_notify_blocks","gve_alloc_queue_page_list",
"gve_tx_alloc_rings","dm_table_create","hci_conn_hold",
"hci_conn_hash_lookup_handle","hci_dev_get","hci_get_route",
"hci_dev_lock","hci_alloc_dev","hci_register_cb",
"hfsplus_find_init","hid_device_io_start","hlist_bl_lock",
"rcu_read_lock","dma_alloc_coherent","hpsa_alloc_ioaccel1_cmd_and_bft",
"dma_alloc_coherent","hpsa_alloc_ioaccel2_cmd_and_bft","dma_alloc_coherent",
"hpsa_alloc_sas_node","hpsa_alloc_sas_port","htab_lock_bucket",
"hwsim_register_virtio_driver","i2c_get_adapter","i915_active_acquire",
"i915_audio_component_get_power","i915_block_alloc","i915_gem_context_lock_engines",
"i915_gem_object_create_stolen","i915_gem_object_lookup","i915_gem_object_lock",
"i915_gem_object_lock_interruptible","ibdev_dbg","to_siw_dev",
"get_net_ns_by_fd","ib_device_get_by_index","ib_device_get_by_netdev",
"rxe_get_dev_from_net","ib_device_register_rdmacg","ibdev_get_unused_vector",
"ib_dma_map_sg","ib_dma_map_single","ib_dma_unmap_single",
"ib_alloc_cq","ib_mr_pool_get","ib_sa_client_get",
"ib_sa_register_client","ib_register_client","ib_register_mad_agent",
"idr_init","idr_preload","idr_alloc",
"ieee802154_alloc_hw","iget_locked","i_mmap_lock_read",
"in6_dev_get","inet_diag_lock_handler","inet_alloc_ifa",
"inet_getpeer_v4","INIT_LIST_HEAD","f2fs_map_blocks",
"inode_lock","inode_lock_nested","inode_trylock",
"inode_trylock_shared","input_open_device","input_allocate_device",
"input_mt_get_value","input_proc_init","instance_lookup_get",
"intel_backlight_device_register","intel_context_lock_pinned","intel_de_write_fw",
"intel_display_power_get","intel_display_power_get_if_enabled","intel_dsb_enable_engine",
"intel_engine_pm_get_if_awake","intel_engine_pm_get","intel_engine_pm_get_if_awake",
"intel_frontbuffer_get","intel_gt_pm_get","intel_runtime_pm_get",
"intel_runtime_pm_get_raw","intel_runtime_pm_get_raw","intel_tc_port_lock",
"intel_uncore_forcewake_get","io_ctl_map_page","io_mem_alloc",
"iommu_attach_device","iommu_group_get","vfio_group_get_from_iommu",
"io_ring_submit_lock","ioremap","iounmap",
"vzalloc","ipoib_neigh_alloc","ipoib_neigh_get",
"ipoib_register_debugfs","ip_set_alloc","ip_set_get_byname",
"ip_set_type_lock","ext4_xattr_inode_iget","f2fs_pagecache_get_page",
"get_pipe_inode","hfsplus_create_cat","iget5_locked",
"iput","ocfs2_get_system_file_inode","ocfs2_get_truncate_log_info",
"ip_vs_scheduler_get","ip_vs_use_count_inc","irq_domain_alloc_named_id_fwnode",
"irq_get_desc_buslock","irq_get_desc_lock","irq_lock_sparse",
"iscsi_host_alloc","kvcalloc","__rdma_create_id",
"is_namespace_pmem","j1939_priv_get","j1939_session_get_by_addr",
"j1939_sk_get_incomplete_session","jbd_lock_bh_journal_head","journal_begin",
"journal_alloc_journal_head","kcmp_lock","kcov_remote_start_usb",
"kernel_param_lock","kernfs_get_active","kernfs_get",
"acpi_evaluate_object","acpi_pci_link_allocate_irq","adf_ctl_alloc_resources",
"alloc_cpumask_var","alloc_indirect_packed","alloc_info_private",
"alloc_path_for_send","alloc_smp_req","alloc_tr",
"alloc_tty_driver","audit_alloc_mark","btrfs_alloc_path",
"build_path_from_dentry","__builtin_expect","cifs_convert_path_to_utf16",
"dma_resv_list_alloc","get_UCSname","__ib_alloc_pd",
"ib_alloc_ucontext","intel_connector_alloc","intel_sdvo_connector_alloc",
"ip6t_alloc_initial_table","ip_options_get_alloc","ipt_alloc_initial_table",
"irq_create_affinity_masks","kasprintf","kcalloc",
"kcalloc_node","kfree","kmalloc",
"kmalloc_array","kmalloc_node","__kmalloc_reserve",
"kmemdup","krealloc","kref_init",
"kstrdup","kzalloc","kzalloc_node",
"media_create_pad_link","memcpy","mon_alloc_buff",
"mtd_kmalloc_up_to","mutex_lock_nested","nfc_llcp_build_tlv",
"nfs4_label_alloc","nfs_alloc_fhandle","nft_trans_alloc",
"nft_trans_alloc_gfp","ocfs2_dx_dir_kmalloc_leaves","ocfs2_local_alloc_reserve_for_window",
"pcistub_device_alloc","printk","read_blk",
"ring_buffer_alloc_read_page","simple_xattr_alloc","__alloc_skb",
"alloc_skb","alloc_skb_with_frags","bt_skb_alloc",
"bt_skb_send_alloc","clone_skb","genlmsg_put",
"hci_get_drvdata","ip_hdr","ipv6_hdr",
"_l2_alloc_skb","nci_skb_alloc","netdev_priv",
"nfc_alloc_recv_skb","nfc_alloc_send_skb","nlmsg_new",
"ovs_dp_cmd_alloc_info","ovs_vport_cmd_alloc_info","pskb_may_pull",
"skb_dst","skb_pull","skb_reset_network_header",
"SKB_TO_PKT","skb_transport_offset","sk_stream_alloc_skb",
"sock_alloc_send_pskb","sock_alloc_send_skb","slhc_init",
"strstrip","tipc_aead_mem_alloc","ucma_alloc_ctx",
"uvc_alloc_chain","xhci_alloc_command","xhci_ring_alloc",
"kmem_cache_create","f2fs_kmem_cache_alloc","idr_alloc_cyclic",
"kmem_cache_alloc","kmem_cache_zalloc","kmem_zone_zalloc",
"kmem_alloc","kmem_zalloc","xlog_alloc_buffer",
"kobject_create_and_add","kobject_get","kobject_init",
"kobject_init_and_add","iwpm_find_nlmsg_request","kref_get",
"kset_create_and_add","kmap","kunmap",
"btrfs_alloc_path","ceph_kvmalloc","f2fs_kmalloc",
"f2fs_kvzalloc","gve_alloc_queue_page_list","iov_iter_get_pages_alloc",
"kmalloc","kvcalloc","kvmalloc",
"kvmalloc_array","kvzalloc","kzalloc",
"nf_ct_alloc_hashtable","simple_xattr_alloc","kmalloc",
"kzalloc","vzalloc","l2cap_chan_lock",
"leb_write_lock","leb_write_trylock","list_add",
"list_add_tail","local_bh_disable","lockd_up",
"lock_acquire","locks_alloc_lock","in6_dev_get",
"macsec_rxsc_get","md_bitmap_storage_alloc","mddev_lock",
"mdiobus_register_device","media_create_pad_link","media_device_register_entity",
"media_entity_pads_init","media_add_link","media_create_pad_link",
"media_request_get","memcg_get_cache_ids","idr_alloc",
"mem_cgroup_id_get_online","mempool_alloc","memremap",
"mix_psk","mesh_table_alloc","mgmt_cmd_complete",
"mutex_lock_nested","mgmt_cmd_status","mutex_lock_nested",
"migrate_read_lock","misc_register","mkiss_get",
"mlx4_bitmap_alloc","mlx4_buddy_alloc","mlx4_counter_alloc",
"mlx4_cq_alloc_icm","mlx4_cq_alloc","mlx4_cq_alloc",
"mlx4_ib_alloc_eqs","mlx4_mpt_alloc_icm","mlx4_mr_hw_get_mpt",
"mlx4_pci_enable_device","mlx4_counter_alloc","mlx4_mr_alloc",
"mlx4_pd_alloc","mlx4_qp_alloc","mlx4_grant_resource",
"mlx4_srq_alloc_icm","mlx4_counter_alloc","mlx4_uar_alloc",
"mlx4_register_mac","mlx4_xrcd_alloc","mmap_read_lock",
"mmap_read_trylock","mmap_write_lock_killable","mmap_write_lock",
"mmap_write_lock_killable","mm_pkey_alloc","mnt_want_write_file",
"get_default_subvol_objectid","kobject_create_and_add","module_alloc",
"blkdev_get_by_path","__ip_vs_pe_getbyname","__module_get",
"__request_module","try_module_get","mpi_alloc",
"get_vma_policy","__mutex_init","cgroup_lock_and_drain_offline",
"epoll_mutex_lock","ffs_mutex_lock","find_table_lock",
"lockdep_rcu_suspicious","lock_is_held","mutex_lock_interruptible_nested",
"mutex_lock_killable_nested","mutex_lock_nested","mutex_trylock",
"nfsd4_find_and_lock_existing_open","_raw_write_lock_bh","rcu_read_lock",
"reiserfs_mutex_lock_safe","namespace_lock","netdev_name_node_head_alloc",
"netif_addr_lock_bh","netif_tx_lock_bh","netlink_kernel_create",
"netlink_lock_table","netlink_register_notifier","netpoll_poll_lock",
"nf_conntrack_register_notifier","nfc_get_device","nf_ct_expect_related",
"nfnetlink_has_listeners","nfnetlink_subsys_register","debug_lockdep_rcu_enabled",
"nfnl_lock","nfs4_alloc_createdata","nfs4_label_alloc",
"nfs4_proc_getattr","get_lock_access","nfs4_get_stateowner",
"get_lock_access","IS_ERR","nfs4_label_alloc",
"nfs_alloc_fattr","nfs_alloc_fhandle","nfs_create_request",
"nfs_create_rpc_client","nfs_create_request","nft_unregister_expr",
"nf_register_sockopt","nla_nest_start_noflag","nla_put_u32",
"nla_nest_start_noflag","nla_put_u32","nla_put_u32",
"nlmsg_put","genlmsg_put","nl80211hdr_put",
"nlmsg_free","nlmsg_new","nlmsvc_create_block",
"nr_node_get","ntfs_index_ctx_get","nvdimm_bus_lock",
"nvdimm_get_key_payload","nvdimm_get_user_key_payload","lockdep_init_map",
"nvme_enable_streams","nvme_fc_ctrl_get","nvme_fc_lport_get",
"nvme_fc_rport_get","__nvme_find_get_subsystem","nvme_rdma_alloc_io_queues",
"nvme_rdma_alloc_qe","nvme_rdma_alloc_queue","nvme_tcp_alloc_admin_queue",
"nvme_tcp_alloc_io_queues","nvmet_fc_tgtport_get","kzalloc",
"nvmet_check_transfer_len","nvmet_req_init","trace_nvmet_req_init",
"nvmet_find_get_subsys","nv_start_rxtx","o2net_init_nst",
"o2net_set_advance_start_time","o2net_register_hb_callbacks","o2nm_get_node_by_ip",
"o2nm_node_get","o2nm_lock_subsystem","kzalloc",
"ocfs2_dx_dir_kmalloc_leaves","ocfs2_init_dealloc_ctxt","ocfs2_local_alloc_reserve_for_window",
"ocfs2_lock_allocators","ocfs2_lock_refcount_allocators","ocfs2_lock_reflink_xattr_rec_allocators",
"ocfs2_reflink_lock_xattr_allocators","trace_ocfs2_rename","ocfs2_new_path_from_et",
"ocfs2_alloc_quota_recovery","inode_lock","ocfs2_inode_lock_full_nested",
"ocfs2_read_inode_block_full","ocfs2_refcount_tree_get","ocfs2_reflink_remap_blocks",
"ocfs2_init_dealloc_ctxt","ocfs2_stack_driver_get","ocfs2_lock_global_qf",
"ocfs2_lock_refcount_tree","ocfs2_xattr_bucket_new","option_inquiry",
"ovs_lock","p9_req_try_get","page_ref_add",
"path_get","path_put","pci_config_pm_runtime_get",
"pci_get_device","pci_get_domain_bus_and_slot","pci_get_slot",
"pci_dev_trylock","pci_enable_device","pci_enable_device_mem",
"pci_enable_msi","pci_enable_msix_exact","pci_enable_msix_range",
"pci_enable_pcie_error_reporting","pci_iomap_range","pci_create_resource_files",
"dev_printk","pci_lock_rescan_remove","pci_map_rom",
"proc_alloc_inum","percpu_down_write","perf_ctx_lock",
"_raw_spin_lock","perf_pmu_disable","phonet_proto_get",
"phy_pm_runtime_get_sync","phy_pm_runtime_get_sync","ping_set_saddr",
"pipe_double_lock","__pipe_lock","pipe_lock",
"platform_device_register_data","hwsim_register_virtio_driver","__platform_driver_register",
"plt_clk_register_fixed_rate","pm_autosleep_lock","pmd_write_lock",
"pm_runtime_enable","pm_runtime_get_sync","pm_runtime_get_sync",
"pm_runtime_get_noresume","pm_runtime_get_sync","pm_runtime_get_noresume",
"pm_runtime_get_sync","pm_runtime_get_sync","pm_runtime_get_sync",
"pm_runtime_set_active","posix_acl_create_masq","pps_lock",
"proc_alloc_inum","kzalloc","proto_register",
"pop","page_get_anon_vma","get_busid_priv",
"get_clock_desc","get_cred","nfs4_get_clid_cred",
"security_dentry_create_files_as","get_css_set","acpi_bus_get_device",
"device_initialize","device_register","dev_printk",
"get_device","kzalloc","scsi_alloc_target",
"get_dev_pagemap","__alloc_disk_node","get_files_struct",
"get_fs_type","get_futex_key","__get_ns_from_inode",
"get_journal_list","create_lkb","get_net",
"get_proc_net","maybe_get_net","get_online_cpus",
"get_online_mems","alloc_pages","find_get_page",
"find_get_pages_range_tag","find_or_create_page","get_page",
"get_page_unless_zero","__get_user_pages_locked","get_user_pages_remote",
"iov_iter_get_pages_alloc","page_cache_get_speculative","put_page",
"vaddr_get_pfn","get_task_struct","get_pipe_version",
"_get_res","get_current_rng","hold_rsb",
"__get_seccomp_filter","get_space","get_swap_device",
"find_get_page","__get_system","find_get_task_by_vpid",
"get_files_struct","get_pid_task","get_proc_task",
"get_task_mm","get_task_struct","get_free_tei",
"alloc_tty_driver","__get_unused_fd_flags","get_unused_fd_flags",
"sock_create","get_vaddr_frames","get_workspace",
"dev_get_drvdata","qat_alg_sgl_to_bufl","qat_crypto_get_instance_node",
"qat_rsa_set_d","qdisc_priv","qdisc_create_dflt",
"queued_spin_lock","get_futex_value_locked","queue_lock",
"read_blk","raid5_get_active_stripe","_raw_read_lock_bh",
"_raw_read_lock","trace_btrfs_tree_read_lock_enabled","_raw_spin_lock_bh",
"lock_is_held","_raw_spin_lock_irq","_raw_spin_lock",
"_raw_spin_lock_irq","_raw_write_lock_bh","_raw_write_lock_irq",
"_raw_write_lock","rcu_read_lock","rcu_read_lock_bh",
"spin_lock_bh","debug_lockdep_rcu_enabled","rcu_read_lock",
"rcu_read_lock_held","read_seqbegin_or_lock","rq_unpin_lock",
"spin_lock","uapi_get_object","rdma_counter_get_qp",
"rdma_rw_map_sg","rdma_fill_sgid_attr","rds_ib_get_client_data",
"rds_ib_get_device","kmem_cache_alloc","regmap_debugfs_init",
"regulator_bulk_register_supply_alias","reiserfs_init_alloc_options","reiserfs_write_lock",
"request_firmware","__get_metapage","JFS_IP",
"gfs2_iomap_get","__request_region","dev_get_by_index_rcu",
"ieee802154_get_dev","lock_sock","release_sock",
"proc_create_net_data","proc_create_seq_private","proc_mkdir",
"add_wait_queue","rhashtable_walk_start","__ring_buffer_alloc",
"ring_buffer_get","__rmi_register_function_handler","rmw_set_fw",
"xprt_switch_get","rpc_clnt_debugfs_register","rpc_register_client",
"__alloc_percpu_gfp","rtnl_link_register","rtnl_lock",
"rtnl_lock","rtnl_trylock","rtrs_iu_alloc",
"rvt_alloc_rq","rvt_get_mr","sas_port_alloc",
"sas_register_ports","sb_start_pagefault","dma_map_single_attrs",
"scsi_autopm_get_target","scsi_device_get","scsi_eh_prep_cmnd",
"scsi_host_get","scsi_host_lookup","scsi_log_reserve_buffer",
"sdata_lock","sdw_acquire_bus_lock","mgmt_cmd_status",
"serial8250_rpm_get","sess_alloc_buffer","sg_alloc_table_chained",
"sg_alloc_table","sg_alloc_table_from_pages","kmalloc",
"skb_dequeue","crypto_alloc_skcipher","skcipher_request_alloc",
"skcipher_unmap_src","sk_alloc","sk_psock_get",
"SMB2_sess_alloc_buffer","smbd_disconnect_rdma_connection","smc_ism_get_vlan",
"smc_cdc_get_free_slot","snd_hda_codec_pcm_get","snd_hdac_power_up_pm",
"snd_hdac_power_up","snd_info_create_module_entry","snd_media_start_pipeline",
"_snd_pcm_stream_lock_irqsave","snd_pcm_stream_lock_irq","sock_kmalloc",
"lock_sock","mptcp_pm_get_local_id","spin_lock",
"__sock_create","sock_create","sock_create_kern",
"sock_create_lite","spi_alloc_device","spi_dev_get",
"_atomic_dec_and_lock","spin_lock_bh","btrfs_map_sblock",
"__builtin_expect","find_lock_page","inode_lock",
"_raw_spin_lock_irqsave","spin_lock","__rwlock_init",
"spin_lock_irq","usb_lock_device_for_reset","lockd_up",
"lock_is_held","locks_insert_lock_ctx","lock_sock",
"nf_conntrack_lock","pmd_lock","__pmd_trans_huge_lock",
"pmd_trans_huge_lock","pud_lock","__raw_spin_lock_init",
"_raw_spin_lock_nested","rcu_read_lock_held","read_seqbegin_or_lock",
"spin_lock","spin_trylock","trace_ocfs2_dentry_attach_lock",
"unlock_new_inode","xfs_ilock","spi_set_cs",
"sp_get","squashfs_cache_get","squashfs_get_datablock",
"srcu_read_lock","sta_info_alloc","strcmp",
"kzalloc","strncmp","stub_device_alloc",
"subdev_fh_init","svc_rdma_send_ctxt_get","svc_start_kthreads",
"__symbol_get","xen_sysfs_properties_init","sysfs_create_group",
"xen_sysfs_properties_init","sysfs_create_link","sysfs_streq",
"task_rq_lock","update_rq_clock","task_lock",
"tb_ring_start","tb_tunnel_alloc","tb_tunnel_alloc_pci",
"tb_tunnel_alloc_usb3","setup_sgtable","thermal_cooling_device_register",
"tipc_bcast_lock","tipc_node_read_lock","spin_lock_bh",
"tls_get_ctx","tpm_buf_init","tpm_find_get_ops",
"tpm_try_get_ops","trace_array_get","tracing_check_open_get_tr",
"tracing_check_open_get_tr","tracefs_create_dir","trace_i915_request_wait_begin",
"trace_mm_compaction_begin","nfs4_set_lock_state","trace_ocfs2_get_dentry_begin",
"trace_ocfs2_iget_begin","trace_ocfs2_query_inode_wipe_begin","trace_ocfs2_queue_orphan_scan_begin",
"trace_parser_get_init","trace_suspend_resume","bpf_prog_run_xdp",
"xfs_alloc_get_rec","trace_xfs_rmap_unmap","bus_register",
"transport_setup_device","ttm_bo_reserve","ttm_mem_global_alloc",
"ttm_mem_io_lock","kmalloc_array","ttm_write_lock",
"tty_alloc_file","tty_port_tty_get","tty_ldisc_ref",
"tty_lock","tty_register_device","tty_register_ldisc",
"tty_write_lock","tun_get","u64_stats_update_begin",
"__builtin_constant_p","__builtin_constant_p","__builtin_expect",
"printk","ubi_dbg_chk_io","ubi_io_read",
"ubi_alloc_vid_buf","ubifs_assert_failed","ubifs_err",
"ubifs_budget_space","ubifs_release_budget","ubifs_get_lprops",
"ubi_get_device","ubi_wl_get_peb","udp_sock_create",
"ulist_alloc","irq_set_chip_and_handler_name","unix_state_double_lock",
"unix_sysctl_register","shadow_ablock","lock_buffer",
"lock_cluster_or_swap_info","lock_device_hotplug","lock_parent",
"lock_extent_bits","try_lock_extent","lock_fat",
"lock_fs","lock_journal","lock_mount_hash",
"__builtin_expect","find_lock_page","fscrypt_encrypt_pagecache_blocks",
"lock_page","lock_page_maybe_drop_mmap","lock_page_memcg",
"spin_lock","trylock_page","lock_rdev",
"lock_rsb","lock_system_sleep","lock_two_nondirectories",
"map_mft_record","ntfs_mft_bitmap_find_and_alloc_free_rec_nolock","register_blkdev",
"alloc_chrdev_region","register_chrdev_region","register_chrdev",
"register_device","register_filesystem","register_inet6addr_notifier",
"register_inet6addr_validator_notifier","register_inetaddr_notifier","register_inetaddr_validator_notifier",
"register_netdevice_notifier","register_netdev","register_net_sysctl",
"hwsim_register_virtio_driver","register_pernet_device","register_netdevice_notifier",
"register_pernet_subsys","register_reboot_notifier","register_filesystem",
"register_sysctl_table","register_trace_sched_wakeup","set_reloc_control",
"down","down_interruptible","down_trylock",
"down_read","up_read","down_write",
"up_write","kzalloc","usb_get_intfdata",
"usb_autopm_get_interface","usb_autoresume_device","usb_ep_queue",
"usb_ep_alloc_request","usb_alloc_coherent","usb_alloc_urb",
"usbfs_increase_memory_usage","usb_hcd_link_urb_to_ep","usb_create_shared_hcd",
"usb_hcd_link_urb_to_ep","usb_create_hcd","usb_create_shared_hcd",
"usb_get_intf","usb_get_descriptor","usb_create_hcd",
"usb_anchor_urb","usb_unlocked_disable_lpm","user_path_at",
"usnic_vnic_get_resources","v4l2_device_register","v4l2_m2m_register_media_controller",
"v4l2_fh_add","v4l2_fh_init","v4l2_m2m_register_media_controller",
"v9fs_cache_register","__vb2_init_fileio","ib_register_mad_agent",
"cur_regs","vfio_device_get_from_dev","vfio_group_get_from_minor",
"vmalloc","__vmalloc","__vmalloc_node",
"vmalloc_user","vzalloc","xt_counters_alloc",
"kvmalloc","register_instance","v4l2_m2m_register_media_controller",
"virtio_gpu_array_lock_resv","virtio_transport_alloc_pkt","virtio_transport_get_credit",
"vlv_punit_get","vma_get_pages","vm_area_alloc",
"vm_alloc_page","vmw_cmdbuf_cur_lock","vmw_fifo_resource_inc",
"enic_wq_devcmd2_alloc","map_kernel_range","mutex_lock_nested",
"wc_lock","wdev_lock","wpan_phy_register",
"get_hwbase","netdev_priv","write_seqcount_begin",
"write_seqlock_bh","write_seqlock","x25_get_neigh",
"x25_get_route","kzalloc","xenbus_dev_fatal",
"xenbus_scanf","xenbus_alloc_evtchn","kcalloc",
"xenvif_init_hash","connect_ctrl_ring","xfrm_get_tos",
"xfrm_register_type","fs_dax_get_by_bdev","xfs_blkdev_get",
"xfs_da_state_alloc","mutex_lock_nested","xfs_dqlock",
"xfs_dqlock_nowait","lockdep_rcu_suspicious","xfs_ilock",
"xfs_ilock_attr_map_shared","xfs_ilock_data_map_shared","xfs_ilock_nowait",
"xfs_inode_free_quota_cowblocks","xfs_lock_two_inodes","xfs_alloc_get_rec",
"xfs_perag_get","xfs_qm_dqget","xfs_sysctl_register",
"xfs_trans_alloc","_dev_warn","xhci_alloc_command",
"xhci_alloc_command_with_ctx","xhci_ring_alloc","xhci_ring_alloc",
"xhci_segment_alloc","dma_map_page_attrs","test_and_set_bit",
"kzalloc","xprt_get","xprt_switch_get",
"xt_alloc_table_info","xt_percpu_counter_alloc"};
